import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-8 mb-8 bg-gray-300">
          <ul className="flex justify-evenly">
            <li className="bg-transparent p-5 rounded-xl shadow-xl">
              <Link href="/">Home</Link>
            </li>
            <li className="bg-transparent p-5 rounded-xl shadow-xl">
              <Link href="/performance">Performance</Link>
            </li>
            <li className="bg-transparent p-5 rounded-xl shadow-xl">
              <Link href="/reliability">Reliability</Link>
            </li>
            <li className="bg-transparent p-5 rounded-xl shadow-xl">
              <Link href="/scale">Scale</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
